spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/skyscapehub?currentSchema=iam-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 1000ms

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Optional: for logging SQL with parameter values
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org:
      springframework:
        data:
          redis=DEBUG:
server:
  servlet:
    context-path: /iam